sudo: false
language: c
env:
  global:
addons:
  apt:
    packages:
    - docbook
    - docbook-dsssl
    - docbook-xsl
    - libbsd-dev
    - libedit-dev
    - libosp5
    - libostyle1c2
    - libpam0g-dev
    - libperl-dev
    - libperl5.14
    - libpython3.2
    - openjade
    - opensp
    - python3
    - python3-dev
    - python3-minimal
    - python3.2
    - python3.2-dev
    - python3.2-minimal
    - tcl8.5
    - tcl8.5-dev
    - xsltproc
script:
  - ./configure && make docs
  - cd doc/src/sgml
  - xmllint --noout --valid postgres.xml
  - mv html html4
#  - travis_wait 30 make xslthtml
#  - mv html xhtml
after_success:
  - zip -r doc-ja.zip html4 xhtml man1 man3 man7
  - cd ../../..
  - mkdir build
  - mv doc/src/sgml/doc-ja.zip build
deploy:
  provider: gcs
  access_key_id: GOOG7OE55GJJN7GHSYQQ
  secret_access_key:
    secure: JFDYGy1g3Tp+ouuIRsheuQL0ynNefvy2QMZMKTHpDX/g37WWLJL4TYThZtuVTTS8oWt7s+6n2XXpT9NJSMUj9Jr+UgR8q3Q4KoOAVeoj2MahxHsUbqAQTY+6LhaoE4t1BcH5+CWNCmDk6ku7IRuaziOcpaIDgu8MC5v93sHqOEc=
  bucket: jpug-doc-test
  local_dir: build
  skip_cleanup: true
  on:
    repo: noborus/jpug-doc
    branch: travis_doc
