name: make test

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: Install Dependencies
      run: sudo apt install -y docbook-xsl libbsd-dev libedit-dev libpam0g-dev libperl-dev libxml2-utils xsltproc
    - name: configure
      run: ./configure
    - name: make
      run: make docs "XSLTPROCFLAGS= --stringparam suppress.footer.navigation '1'"
